# Generated by Django 3.0.6 on 2020-05-10 18:12

from django.db import migrations, models
import django.db.models.deletion
import patientApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Patient Name')),
                ('age', models.IntegerField(validators=[patientApp.models.ageValidate], verbose_name='Age')),
                ('aadharNumber', models.CharField(max_length=12, validators=[patientApp.models.aadharValidate], verbose_name='Aadhar Number')),
                ('bloodGrp', models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], default='B+', max_length=3, verbose_name='Blood group')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=15, validators=[patientApp.models.phoneValidate], verbose_name='Phone Number')),
                ('disease', models.CharField(max_length=30, verbose_name='Disease')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportfile', models.FileField(upload_to='patientApp/')),
                ('reportType', models.CharField(choices=[('Accident and emergency (A&E)', 'Accident and emergency (A&E)'), ('Admissions', 'Admissions'), ('Breast Screening', 'Breast Screening'), ('Burn Center', 'Burn Center'), ('Cardiology', 'Cardiology'), ('CSSD', 'Central Sterile Services Department (CSSD)'), ('Chaplaincy', 'Chaplaincy'), ('CCU', 'Coronary Care Unit'), ('Critical Care', 'Critical Care'), ('Diagnostic Imaging', 'Diagnostic Imaging'), ('Discharge Lounge', 'Discharge Lounge'), ('Elderly services', 'Elderly services'), ('Finance Department', 'Finance Department'), ('Gastroenterology', 'Gastroenterology'), ('General Services', 'General Services'), ('General Surgery', 'General Surgery'), ('Haematology', 'Haematology'), ('Health & Safety', 'Health & Safety'), ('ICU', 'Intensive Care Unit (ICU)')], default='Accident and emergency (A&E)', max_length=30)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientApp.Patient')),
            ],
        ),
    ]
