# Generated by Django 3.0.6 on 2020-05-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientImgReport',
            field=models.ImageField(upload_to='patientApp/reportImages/', verbose_name='Uploaded report'),
        ),
    ]
