# Generated by Django 3.0.5 on 2020-05-27 16:11

from django.db import migrations, models
import patientApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadharNumber',
            field=models.CharField(max_length=12, unique=True, validators=[patientApp.models.aadharValidate], verbose_name='Aadhar Number'),
        ),
    ]
