# Generated by Django 3.0.5 on 2020-05-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patientImgReport',
        ),
    ]
