# Generated by Django 3.0.5 on 2020-05-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0002_remove_patient_patientimgreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportfile', models.FileField(upload_to='patientApp/')),
                ('dateCreated', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientApp.Patient')),
            ],
        ),
    ]
