# Generated by Django 3.0.5 on 2020-05-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('General', 'General'), ('Opthalmologist', 'Opthalmologist'), ('OPD', 'OPD'), ('XRAY', 'XRAY'), ('Pathologist', 'Pathologist')], default='General', max_length=100),
        ),
    ]
