# Generated by Django 3.0.5 on 2020-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docManagement', '0002_auto_20200511_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Accident and emergency (A&E)', 'Accident and emergency (A&E)'), ('Admissions', 'Admissions'), ('Breast Screening', 'Breast Screening'), ('Burn Center', 'Burn Center'), ('Cardiology', 'Cardiology'), ('CSSD', 'Central Sterile Services Department (CSSD)'), ('Chaplaincy', 'Chaplaincy'), ('CCU', 'Coronary Care Unit'), ('Critical Care', 'Critical Care'), ('Diagnostic Imaging', 'Diagnostic Imaging'), ('Discharge Lounge', 'Discharge Lounge'), ('Elderly services', 'Elderly services'), ('Finance Department', 'Finance Department'), ('Gastroenterology', 'Gastroenterology'), ('General Services', 'General Services'), ('General Surgery', 'General Surgery'), ('Haematology', 'Haematology'), ('Health & Safety', 'Health & Safety'), ('ICU', 'Intensive Care Unit (ICU)'), ('Dental', 'Dental'), ('Opthalmologist', 'Opthalmologist')], default='General', max_length=100),
        ),
    ]
